pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - title~=(^(build|chore)\(deps\):\s+[B|b]ump [^\s]+ from ([\d]+)\..+ to \d+)|(^Bump [^\s]+ from ([\d]+)\..+ to \1\.)
    actions:
      merge:
        method: merge
